-- AlterTable
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "showOnTelegram" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "isFeatured" BOOLEAN NOT NULL DEFAULT false;
